config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :users
  root to: 'welcome#index'

  get "projects/:project_id/add_member" => "projects#add_member", :as => "add_member"

  match "projects/:project_id/add_member_to_project" => "projects#add_member_to_project",
        :as => "add_member_to_project",
        :via => [:post, :patch]

  resources :projects, except: [:show, :index] do

  resources :categories, only: :edit

    resources :categories do
      resources :posts do
        resources :comments, module: :posts
      end

      resources :assets do 
        resources :comments, module: :assets
        resource :like, module: :assets
      end
    end
  end

  match "projects/:project_id/categories/:categories_id/:type" => "assets/file_types#show", 
      :as => "assets_content_type", 
      via: :get

  scope path: '/projects', controller: :projects do
    get '' => :index
    get ':project_id' => :show
  end

  scope path: '/projects', controller: :assets do
    get ':project_id/:category_id/:id' => :show
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  extend FriendlyId
  resourcify

  # Unfortunately, Rails 4.2.2 still doesn't have a way to pass a prefix to enums
  # This will be officially added in Rails 5.
  enum status: { is_private: 0, is_public: 1, is_team: 2 }

  friendly_id :title, use: :slugged

  # Validations
  validates_presence_of :title, :description


  # Associations
  has_many :assets, dependent: :destroy
  belongs_to :user

  has_many :collaborations
  has_many :users, through: :collaborations

  has_many :categories

  has_many :posts

  scope :public_projects, -> { where("status = ?", Project.statuses[:is_public]) }

  # Returns global and non-global categories
  # def visible_categories
  #   global = Category.where(global: true)
  #   no_global = categories.where(global: false)
  #   global.concat(no_global).uniq.sort
  # end

  def collaborators
    users.where.not(name: user.name)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = current_user
    @projects = @user.all_projects
  end

  def show
    @users = User.all
    @project = Project.friendly.find(params[:project_id])
    @members = User.where.not(id: @project.user.id)
    @categories = Category.all
    
    authorize @project
  end

  def new
    @project = Project.new

    authorize @project
  end

  def create
    @user = current_user
    @project = @user.created_projects.create(project_params)

    authorize @project
    if @project.save
      flash[:notice] = "The project has been created."
      redirect_to project_path(@project)
    else
      flash[:error] = "The project could not be created, please try again."
      render 'new'
    end
  end

  def edit
    @project = Project.friendly.find(params[:id])
    authorize @project
  end

  def update
    @project = Project.friendly.find(params[:id])
    authorize @project
    if @project.update_attributes(project_params)
      flash[:notice] = "The project has been updated."
      redirect_to @project
    else
      flash[:error] = "The project cannot be updated."
      render @project
    end
  end

  def destroy
    @project = Project.friendly.find(params[:id])
    authorize @project
    if @project.destroy
      flash[:notice] = "The project has been deleted."
      redirect_to projects_path
    else
      flash[:error] = "The project cannot be deleted."
      render @project
    end
  end

  def add_member
    project = Project.friendly.find(params[:project_id])
    respond_to do |format|
      format.html { redirect_to project_path(project), notice: "This URL cannot be accessed directly." }
      format.js   { render nothing: true }
    end
  end

  def add_member_to_project
    @project = Project.friendly.find(params[:project_id])

    if @project.update_attributes(project_params)
      user_ids = params[:project][:user_ids]

      user_ids.map do |user|
        @project.collaborations.build(user_id: user)
      end

      flash[:notice] = "Member added."
      redirect_to project_path(@project.friendly_id)
    else
      flash[:danger] = "Member couldn't be added"
      render 'show'
    end
  end

  private

  def project_params
    params.require(:project).permit(:title, :description, :status, :user_ids => [])
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_project.html.erb
<li class="project" id="project-<%= project.id %>" >
  <%= link_to project.title, project_path(project.slug) %> <br>
  <%= project.description %>
</li>

app/views/projects/edit.html.erb
<div class="container">
<div class="row">
  <div class="col-md-4">
    <h1>Update Project</h1>
    <%= form_for @project do |f| %>
      <%= render "shared/errors", object: @project %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, rows: 10, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.select :status, Project.statuses.keys.map { |status| [status.gsub(/is_/, "").capitalize, status] } %>
      </div>


      <div class="form-group">
        <%= f.submit "Update Project", class: 'btn btn-success' %>
      </div>
    <% end %>

  </div>
</div>

</div>

app/views/projects/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <h1>Projects</h1>
      <%= link_to "New Project", new_project_path, class: "btn btn-primary" %>

      <% if @projects.any? %>
      <%= render @projects %>
      <% else %>
      <p> There's nothing here, go a head and create a new project. </p>
      <% end %>

    </div>
  </div>
</div>

app/views/projects/new.html.erb
<div class="container">
  <div class="row">
  <div class="col-md-4">
  <h2>Create new project</h2>
    <%= form_for @project do |f| %>
      <%= render "shared/errors", object: @project %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, rows: 10, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.select :status, Project.statuses.keys.map { |status| [status.gsub(/is_/, "").capitalize, status] } %>
      </div>

      <div class="form-group">
        <%= f.submit "Create Project", class: 'btn btn-success' %>
      </div>
    <% end %>

  </div>
</div>

</div>

app/views/projects/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1><%= @project.title %></h1>
      <small>Created by:
				<%= @project.user.name %>
      </small>
      <br>
      <% unless @project.collaborators.empty? %>
        <small>
          Collaborators:
				<%= @project.collaborators.collect(&:name).join(", ") %>
        </small>
      <% end %>
      <div id="button-row">
        <% if policy(@project).edit? %>
          <%= link_to "Edit Project", edit_project_path(@project), class: "btn btn-primary" %>
        <% end %>
        <%= link_to "Create Category", new_project_category_path(@project), class: "btn btn-warning" %>
        <%= link_to "Add Members", add_member_path, class: "btn btn-warning", :data => { toggle: "modal", target: "#add_member" }, remote: true  %>
        <%= render 'users/add_member' %>
        <% if policy(@project).destroy? %>
          <%= link_to "Delete Project", project_path(@project), method: :delete, class: "btn btn-danger", data: { confirm: "Are you sure?" } %>
        <% end %>
      </div>
      <p><%= @project.description %></p>
      <%# TODO: Add a link to assets#index %>
      <%# link_to "All", project_category_assets_path, class: "btn btn-primary" %>
      <h3>Project Categories:</h3>
      <%= render @project.categories %>
    </div>
  </div>
</div>