config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :users
  root to: 'welcome#index'

  get "projects/:project_id/add_member" => "projects#add_member", :as => "add_member"

  match "projects/:project_id/add_member_to_project" => "projects#add_member_to_project",
        :as => "add_member_to_project",
        :via => [:post, :patch]

  resources :projects, except: [:show, :index] do

  resources :categories, only: :edit

    resources :categories do
      resources :posts do
        resources :comments, module: :posts
      end

      resources :assets do 
        resources :comments, module: :assets
        resource :like, module: :assets
      end
    end
  end

  match "projects/:project_id/categories/:categories_id/:type" => "assets/file_types#show", 
      :as => "assets_content_type", 
      via: :get

  scope path: '/projects', controller: :projects do
    get '' => :index
    get ':project_id' => :show
  end

  scope path: '/projects', controller: :assets do
    get ':project_id/:category_id/:id' => :show
  end
end

app/models/asset.rb
class Asset < ActiveRecord::Base

  # External Gems
  extend FriendlyId
  friendly_id :slug_candidates, use: [:slugged, :history]
  mount_uploader :asset_file, AssetItemUploader

  before_save :update_asset_attributes

  # Validations
  validates_presence_of :title, :category

  # Associations
  belongs_to :project
  belongs_to :user
  belongs_to :category


  has_many :likes
  has_many :comments, as: :commentable, dependent: :destroy


  scope :image, -> { where(content_type: 'image') }
  scope :video, -> { where(content_type: 'video') }
  scope :audio, -> { where(content_type: 'audio') }
  scope :filtered_by_type, -> (params, category) { 
      where( "content_type = ? AND category_id = ?", params, category ) 
  }

  # Public Methods

  def slug_candidates
   [
     :title,
     [:title, :title_sequence]
  ]
  end

  def title_sequence
   slug = normalize_friendly_id(title)
   sequence = Asset.where("slug like '#{slug}-%'").count + 2
  end

  def should_generate_new_friendly_id?
   title_changed?
  end

  private

  def update_asset_attributes
    if asset_file.present? && asset_file_changed?
      self.content_type = asset_file.file.content_type.split("/").first
    end
  end
end

app/controllers/assets/comments_controller.rb
class Assets::CommentsController < CommentsController
  before_action :set_commentable
  before_action :set_project
  before_action :set_category

  private

  def set_commentable
    @commentable = Asset.friendly.find(params[:asset_id])
  end

  def set_project
    @project = Project.friendly.find(params[:project_id])
  end

  def set_category
    @category = Category.friendly.find(params[:category_id])
  end

end

app/controllers/assets/file_types_controller.rb
class Assets::FileTypesController < AssetsController

  def show
    @category = Category.friendly.find(params[:categories_id])
    @project = Project.friendly.find(params[:project_id])
    @assets_content_type = Asset.pluck(:content_type).uniq
    @filtered_assets = Asset.filtered_by_type(params[:type], @category)

    file_type = params[:type]
    @assets = Asset.none

    file_type_whitelist = %w{ image video audio application }

    if file_type_whitelist.include?(file_type)
      @assets = @category.assets.send(file_type)
    end
  end
end

app/controllers/assets/likes_controller.rb
class Assets::LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_project, :find_asset, :find_category

  def create
    @asset.likes.where(user_id: current_user.id).first_or_create

    respond_to do |format|
      format.html { redirect_to [@project, @asset] }
      format.js
    end
  end

  def destroy
    @asset.likes.where(user_id: current_user.id).destroy_all

    respond_to do |format|
      format.html { redirect_to [@project, @asset] }
      format.js
    end
  end


  private

  def find_project
    @project = Project.friendly.find(params[:project_id])
  end

  def find_asset
    @asset = Asset.friendly.find(params[:asset_id])
  end

  def find_category
    @category = Category.friendly.find(params[:category_id])
  end
end

app/controllers/assets_controller.rb
class AssetsController < ApplicationController
  before_action :authenticate_user!

  def index
    @project = Project.friendly.find(params[:project_id])
  end

  def show
    @project = Project.friendly.find(params[:project_id])
    @category = Category.friendly.find(params[:category_id])
    @asset = @project.assets.friendly.find(params[:id])
    authorize @asset
  end

  def new
    @asset = Asset.new
    @project = Project.friendly.find(params[:project_id])
  end

  def create
    @project = Project.friendly.find(params[:project_id])
    @asset = @project.assets.create(asset_params)
    @asset.user_id = current_user.id

    category_id = params[:asset][:category_id]

    if category_id
      @category = Category.friendly.find(params[:asset][:category_id])
      @asset.category_id = params[:asset][:category_id]
      @category.assets << @asset
    end

    if @asset.save
      flash[:notice] = 'The asset has been created.'
      redirect_to [@project, @category, @asset]
    else
      flash[:error] = 'Please try again.'
      render 'new'
    end
  end

  def edit
    @asset = Asset.friendly.find(params[:id])
  end

  def update
    @asset = Asset.friendly.find(params[:id])

    if @asset.update_attributes(asset_params)
      flash[:notice] = 'The asset has been updated.'
      redirect_to project_asset_path
    else
      flash[:error] = 'The asset cannot be updated.'
      render 'edit'
    end
  end

  def destroy
    @asset = Asset.friendly.find(params[:id])
    @project = Project.friendly.find(params[:project_id])
    @category = Category.friendly.find(params[:category_id])

    if @asset.destroy
      flash[:notice] = "\"#{@asset.title}\" was deleted successfully."
      redirect_to project_category_path(@project, @category)
    else
      flash[:error] = 'There was an error deleting the asset.'
      render :show
    end
  end

  private

  def asset_params
    params.require(:asset).permit(:title, :asset_file, :remove_asset_file, :description, :tag_list, :category_id, category_ids: [] )
  end
end

app/helpers/assets_helper.rb
module AssetsHelper
end

app/views/assets/_assets.html.erb
<div class="asset-posts-container">
  <% assets.each do |asset| %>
    <div class="col-md-3 asset-post">
      <%= link_to (image_tag asset.asset_file.thumb.url), project_category_asset_path(@project, @category, asset), class: 'asset-thumbnail' if asset.content_type.include?('image') %>
      <%= link_to (image_tag asset.asset_file.video_thumbnail.url), project_category_asset_path(@project, @category, asset), class: 'asset-thumbnail' if asset.content_type.include?('video') %>
      <h4><%= link_to asset.title, project_category_asset_path(@project, @category, asset) %></h4>
       <%# sanitize(truncate(asset.description, length: 100)) %>
      <div class="asset-meta-info">
        <small class="meta-left">
          <% if current_user.avatar.url.present? %>
            <%= image_tag(current_user.avatar.mini.url) %>
          <% end %>
          <%= asset.user.name %>
        </small>
        <div class="meta-right">
          <small class="likes-<%= asset.id %>">
            <%= render partial: "assets/likes", locals: { asset: asset } %>
          </small>
          <small class="comments">
            <%= fa_icon "comments" %> <%= pluralize asset.comments.count, "Comment" %>
          </small>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/assets/_likes.html.erb
<% if user_signed_in? && current_user.likes?(asset) %>

<%= link_to (fa_icon "heart"), project_category_asset_like_path(@project, @category, asset), method: :delete, remote: true %>

<% else %>
<%= link_to (fa_icon "heart-o"), project_category_asset_like_path(@project, @category, asset), method: :post, remote: true %>
<% end %>

<%= asset.likes.count %>

app/views/assets/create.html.erb
<h1>Assets#create</h1>
<p>Find me in app/views/assets/create.html.erb</p>

app/views/assets/destroy.html.erb
<h1>Assets#destroy</h1>
<p>Find me in app/views/assets/destroy.html.erb</p>

app/views/assets/edit.html.erb
<div class="container">
	<div class="row">
	<div class="col-md-4">
		<h1>Edit asset</h1>
		<%= form_for @asset, :url => project_asset_path do |f| %>
		<%= render "shared/errors", object: @asset %>

		<div class="form-group">
			<%= f.label :title %>
			<%= f.text_field :title, class: "form-control" %>
		</div>

		<div class="form-group">
			<%= f.label :description %>
			<%= f.text_area :description, class: 'form-control'  %>
		</div>

		<% if @asset.asset_file? %>
			<%= image_tag @asset.asset_file.thumb.url %>
			<div class="form-group">
				<%= f.label :remove_asset %>
				<%= f.check_box :remove_asset_file%>
			</div>
		<% else %>
			<div class="form-group">
				<%= f.label :upload_asset %>
				<%= f.file_field :asset_file %>
			</div>
			<% end %>

		<div class="form-group">
			<%= f.submit "Update", class: "btn btn-success" %>
		</div>

		<% end %>
	</div>
</div>

</div>

app/views/assets/index.html.erb
<div class="container">
  <div class="row">
<h1>Assets</h1>


<ul>
  <% @project.assets.each do |asset| %>
    <li><%= link_to asset.title, project_asset_path(@project, asset) %></li>
  <% end %>
</ul>

  </div>
</div>

app/views/assets/new.html.erb
<div class="container">
<div class="row">
<div class="col-md-4">
	<h1>New Asset</h1>
	<%= form_for @asset, :url => project_category_assets_path do |f| %>
	<%= render "shared/errors", object: @asset %>

	<div class="form-group">
		<%= f.label :title %>
		<%= f.text_field :title, class: "form-control" %>
	</div>

	<div class="form-group">
		<%= f.label :description %>
		<%= f.text_area :description, class: 'form-control'  %>
	</div>

	<div class="form-group">

		<!-- if category_id then hidden field else show collection_select -->
		<% if params[:category_id] %>
			<%= f.hidden_field :category_id, :value => params[:category_id] %>
		<% else %>
			<%= f.label :select_category %>
			<%= f.collection_select :category_id, @project.categories, :id, :name, { :prompt => "Select a category" }, {:class=>'form-control'} %>
		<% end %>
	</div>

		<div class="form-group">
			<%= f.label :upload_file %>
			<%= f.file_field :asset_file %>
		</div>


	<div class="form-group">
			<%= f.submit "Upload", class: "btn btn-success" %>
	</div>

	<% end %>
</div>
</div>
</div>

app/views/assets/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8">
      <div class="asset-single-container">
        <% if @asset.asset_file.present? %>
          <% if @asset.content_type.include?("image") %>
            <%= link_to (image_tag @asset.asset_file.preview.url), @asset.asset_file.full.url %>
          <% elsif @asset.content_type.include?("application")  %>
            <iframe src=<%= @asset.asset_file.url %> width="600" height="780" style="border: none;"> </iframe>
            <li> <%= link_to "Download", @asset.asset_file.url %> </li>
          <% elsif @asset.content_type.include?("video") %>
            <%= video_tag @asset.asset_file.url, controls: true, width: 700 %>
          <% else %>
            <%= @asset.asset_file.url %>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="asset-single-sidebar">
        <h2><%= @asset.title %></h2>
        <%= link_to "Delete", project_category_asset_path, method: :delete, class: "btn btn-danger", data: { confirm: "Are you sure?" } %>
        <%= link_to "Edit", edit_project_category_asset_path, class: "btn btn-primary" %>
        <div class="likes-<%= @asset.id %>" id="likes">
          <%= render partial: "likes", locals: { asset: @asset } %>
        </div>
        <ul>
          <li>Created by: <%= @asset.user.name %></li>
          <li>Title:  <%= @asset.title %> </li>
          <li>Category:  <%= @asset.category.name %> </li>
          <li>File type: <%= @asset.content_type.capitalize %></li>
          <li>Size: <%= number_to_human_size(@asset.asset_file.file.size) unless @asset.asset_file.file.nil? %></li>
        </ul>
        <h3>Description</h3>
        <p><%= @asset.description %></p>
        <%= render partial: "comments/comments", locals: {commentable: @asset} %>
        <%= render partial: "comments/form", locals: {commentable: @asset} %>
      </div>
    </div>
  </div>
</div>

app/views/assets/update.html.erb
<h1>Assets#update</h1>
<p>Find me in app/views/assets/update.html.erb</p>