config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :users
  root to: 'welcome#index'

  get "projects/:project_id/add_member" => "projects#add_member", :as => "add_member"

  match "projects/:project_id/add_member_to_project" => "projects#add_member_to_project",
        :as => "add_member_to_project",
        :via => [:post, :patch]

  resources :projects, except: [:show, :index] do

  resources :categories, only: :edit

    resources :categories do
      resources :posts do
        resources :comments, module: :posts
      end

      resources :assets do 
        resources :comments, module: :assets
        resource :like, module: :assets
      end
    end
  end

  match "projects/:project_id/categories/:categories_id/:type" => "assets/file_types#show", 
      :as => "assets_content_type", 
      via: :get

  scope path: '/projects', controller: :projects do
    get '' => :index
    get ':project_id' => :show
  end

  scope path: '/projects', controller: :assets do
    get ':project_id/:category_id/:id' => :show
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :project
  belongs_to :category

  has_many :comments, as: :commentable, dependent: :destroy
end

app/controllers/posts/comments_controller.rb
class Posts::CommentsController < CommentsController
  before_action :set_commentable
  before_action :set_project
  before_action :set_category

  private

  def set_commentable
    @commentable = Post.find(params[:post_id])
  end

  def set_project
    @project = Project.friendly.find(params[:project_id])
  end

  def set_category
    @category = Category.friendly.find(params[:category_id])
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    @posts = Post.all
    @project = Project.friendly.find(params[:project_id])
    @category = Category.friendly.find(params[:category_id])
    @assets_content_type = Asset.pluck(:content_type).uniq
  end

  def show
    @post = Post.find(params[:id])
    @project = Project.friendly.find(params[:project_id])
    @category = Category.friendly.find(params[:category_id])
  end

  def new
    @post = Post.new
  end

  def create
    @project = Project.friendly.find(params[:project_id])
    @category = Category.friendly.find(params[:category_id])
    @post = @project.posts.create(post_params)
    @post.user_id = current_user.id
    @post.category_id = @category.id

    if @post.save
      flash[:notice] = "Successfully created..."
      redirect_to [@project, @category, @post]
    else
      render 'new'
    end
  end

  def edit
    @project = Project.friendly.find(params[:project_id])
    @category = Category.friendly.find(params[:category_id])
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @project = Project.friendly.find(params[:project_id])
    @category = Category.friendly.find(params[:category_id])

    if @post.update_attributes(post_params)
      flash[:notice] = "Successfully updated..."
      redirect_to [@project, @category, @post]
    else
      render 'edit'
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/posts/_disqus.html.erb
<div id="disqus_thread"></div>
<script>

var disqus_shortname = 'pixuptestsite';
var disqus_identifier = '<%= @post.id %>';
var disqus_title = '<%= @post.title %>';
var disqus_url = '<%= url_for([@project, @post, { only_path: false }]) %>';


(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');

s.src = '//pixuptestsite.disqus.com/embed.js';

s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

app/views/posts/_post.html.erb
  <li>
      <h3><%= link_to post.title, project_category_post_path(@project, @category, post) %></h3>

      <p><%= post.content %></p>
      <small><%= time_ago_in_words(post.created_at) %></small>
  </li>

app/views/posts/edit.html.erb
<div class="container">
  <div class="row">
<div class="col-md-6">
  <h1>Edit Post</h1>

  <%= form_for [@project, @category, @post] do |f| %>
  <%= render "shared/errors", object: @post %>

  <div class="form-group">
    <%= f.label :title%>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :content%>
    <%= f.text_area :content, class: 'form-control', rows: 20 %>
  </div>

  <div class="form-group">
    <%= f.submit "Update", class: 'btn btn-primary' %>
  </div>

  <% end %>
</div>
</div>

</div>

app/views/posts/index.html.erb
<%= render partial: "categories/categories_menu" %>

<div class="container">
  <div class="row">
    <h1> <%= @project.title %> Posts</h1>

    <ul>
      <%= render @project.posts %>
    </ul>

  </div>
</div>

app/views/posts/new.html.erb
<div class="container">
  <div class="row">
<div class="col-md-6 col-md-offset-3">

  <h1>Add New Post</h1>

  <%= form_for [:project, :category, @post] do |f| %>
  <%= render "shared/errors", object: @post %>

  <div class="form-group">
    <%= f.label :title%>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :content%>
    <%= f.text_area :content, class: 'form-control', rows: 10 %>
  </div>

  <div class="form-group">
    <%= f.submit "Create", class: 'btn btn-success' %>
  </div>

  <% end %>
</div>
</div>

</div>

app/views/posts/show.html.erb
<div class="col-md-8 col-md-offset-3">
<h1><%= @post.title %></h1>

<p><%= @post.content %></p>

 <%= link_to "Edit Post", edit_project_category_post_path %>


 <%= render partial: "comments/comments", locals: {commentable: @post} %>
 <%= render partial: "comments/form", locals: {commentable: @post} %>

<%# render 'disqus' %>



</div>