config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :users
  root to: 'welcome#index'

  get "projects/:project_id/add_member" => "projects#add_member", :as => "add_member"

  match "projects/:project_id/add_member_to_project" => "projects#add_member_to_project",
        :as => "add_member_to_project",
        :via => [:post, :patch]

  resources :projects, except: [:show, :index] do

  resources :categories, only: :edit

    resources :categories do
      resources :posts do
        resources :comments, module: :posts
      end

      resources :assets do 
        resources :comments, module: :assets
        resource :like, module: :assets
      end
    end
  end

  match "projects/:project_id/categories/:categories_id/:type" => "assets/file_types#show", 
      :as => "assets_content_type", 
      via: :get

  scope path: '/projects', controller: :projects do
    get '' => :index
    get ':project_id' => :show
  end

  scope path: '/projects', controller: :assets do
    get ':project_id/:category_id/:id' => :show
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  extend FriendlyId
  friendly_id :slug_candidates, use: [:slugged, :history]

  validates_presence_of :name

  has_many :projects
  has_many :assets, dependent: :destroy
  has_many :posts
  
  belongs_to :user

  scope :global, -> { where( global: true ) }

  def slug_candidates
   [
     :name,
     [:name, :name_sequence]
  ]
  end

  def name_sequence
   slug = normalize_friendly_id(name)
   sequence = Category.where("slug like '#{slug}-%'").count + 2
  end

  def should_generate_new_friendly_id?
   name_changed?
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!

  def index
    @categories = Category.all
  end

  def show
    @assets = Asset.all
    @project = Project.friendly.find(params[:project_id])
    @category = Category.friendly.find(params[:id])
    @assets_content_type = Asset.pluck(:content_type).uniq

    authorize @category
  end

  def new
    @category = Category.new
  end

  def create
    @project = Project.friendly.find(params[:project_id])
    @category = @project.categories.build(category_params)
    @category.user_id = current_user.id
    @category.save!

    if @category.save 
      flash[:notice] = "The category has been created"
      redirect_to project_path(@project)
    else
      flash[:error] = "Could not be created, please try again."
      render 'new'
    end
  end

  def edit
      @project = Project.friendly.find(params[:project_id])
      @category = Category.friendly.find(params[:id])
  end

  def update
    @category = Category.friendly.find(params[:id])
    @project = Project.friendly.find(params[:project_id])

    if @category.update_attributes(category_params)

      flash[:notice] = "The category has been updated"
      redirect_to project_category_path(@project.id, @category)
    else
      flash[:error] = "Could not be updated, please try again."
      render 'edit'
    end
  end

  def destroy
  end

  private

  def category_params
    params.require(:category).permit(:name, :global)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_categories_menu.html.erb
<div class="navbar navbar-default secondary-navigation">
  <div class="container">

  <div class="row">
    <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#secondary-navbar-collapse-1" aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
  </div>

   <div class="collapse navbar-collapse" id="secondary-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "All", project_category_path(@project, @category) %></li>
        <% @assets_content_type.each do |type| %>
          <li><%= link_to (fa_icon "file-#{type}-o", text: "#{type}"), assets_content_type_path(@project, @category, type) if type.present?  %></li>
        <% end %>
        <li> <%= link_to (fa_icon "pencil-square-o", text: "Posts"), project_category_posts_path(@project, @category) %> </li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to (fa_icon "pencil-square-o", text: "Create Post"), new_project_category_post_path(@project, @category) %></li>
       <li><%= link_to (fa_icon "cloud-upload", text: "Upload Asset"), new_project_category_asset_path(@project, @category), class: "btn--asset-upload" %></li>
      </ul>
   </div> <!-- /#secondary-navbar-collapse-1 -->
  </div>
      
  </div>
</div>

app/views/categories/_category.html.erb
<ul>
  <li><%= link_to category.name, project_category_path(@project, category) %></li>
</ul>

app/views/categories/create.html.erb
<h1>Categories#create</h1>
<p>Find me in app/views/categories/create.html.erb</p>

app/views/categories/destroy.html.erb
<h1>Categories#destroy</h1>
<p>Find me in app/views/categories/destroy.html.erb</p>

app/views/categories/edit.html.erb
<div class="container">
  <div class="row">
  <div class="col-md-4">
    <h1>Edit Category</h1>

    <%= form_for [@project, @category] do |f| %>
      <%= render "shared/errors", object: @category %>
      <div class="form-group">
        <%= f.label :category_name, class: "control-label" %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :global %>
        <%= f.check_box :global %>
      </div>
      <%= f.submit "Update", class: 'btn btn-success' %>
    <% end %>
  </div>
</div>

</div>

app/views/categories/index.html.erb
<h1>Categories#index</h1>
<p>Find me in app/views/categories/index.html.erb</p>

app/views/categories/new.html.erb
<div class="container">
  <div class="row">
  <div class="col-md-4">
    <h1>New Category</h1>

    <%= form_for [@project, @category], :url => project_categories_path do |f| %>
      <%= render "shared/errors", object: @category %>
      <div class="form-group">
        <%= f.label :category_name, class: "control-label" %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :global %>
        <%= f.check_box :global %>
      </div>
      <%= f.submit "Create", class: 'btn btn-success' %>
    <% end %>
  </div>
</div>

</div>

app/views/categories/show.html.erb
<%= render partial: "categories_menu" %>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h4> Category: <%= @category.name %> </h4>
      <h3>Assets:</h3>

      <%= link_to "Edit Category", edit_project_category_path(@project, @category), class: 'btn btn-primary' if current_user.has_role? :admin  %>
    </div>
  </div>

  <%= render partial: "assets/assets", locals: { assets: @category.assets } %>
</div>

app/views/categories/update.html.erb
<h1>Categories#update</h1>
<p>Find me in app/views/categories/update.html.erb</p>